version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "terraform"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
