version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/tests/end-to-end-tests"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/tests/integration-tests"
    schedule:
      interval: "daily"