# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/dotnet/format
    rev: v8.0.453106
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format --verbosity diagnostic --include
        types_or: ["c#"]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
