site_name: Azure Immutable Backup
site_description: An [MkDocs](https://www.mkdocs.org/) site for the Azure Immutable Backup documentation.

extra_css:
  - styles.css

theme:
  name: material
  palette:
    - scheme: default
      primary: nhs
  logo: assets/nhs-england-logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - content.tabs.link
    - content.code.copy  
nav:
  - Home: index.md
  - Design: design.md
  - Usage: usage.md
  - Developer Guide: developer-guide.md
  - Pipelines: pipelines.md

markdown_extensions:
  - pymdownx.superfences

copyright: "&copy; NHS England"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NHSDigital/az-backup